{% set name = "aiida-workgraph" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/aiida_workgraph-{{ version }}.tar.gz
  sha256: 9ee72b097dd93a8b514c35ac77bcce1d5da38746b43b514e2eb890b660398b00

build:
  entry_points:
    - workgraph = aiida_workgraph.cli.cmd_workgraph:workgraph
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=3.4,<4
    - pip
  run:
    - jsonschema
    - node-graph-widget >=0.0.4
    - aiida-pythonjob >=0.1.8
    - python >={{ python_min }}
    - numpy >=1.21,<2.dev0
    - scipy
    - ase
    - node-graph ==0.1.27
    - aiida-core >=2.3
    - cloudpickle
    - aiida-shell >=0.8,<1.dev0
    - fastapi
    - uvicorn
    - pydantic-settings

test:
  commands:
    - pip check
    - verdi presto --profile-name test
    - python -c "import aiida_workgraph"
    - workgraph --help
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Design flexible node-based workflow for AiiDA calculation.
  home: https://github.com/aiidateam/aiida-workgraph
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - superstar54
    - jan-janssen
