{% set name = "aiida-workgraph" %}
{% set version = "0.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/aiida_workgraph-{{ version }}.tar.gz
  sha256: a10dba3367e5644f0f3b02a35d0d313c2f06079121ea58c323403fd29343524d

build:
  entry_points:
    - workgraph = aiida_workgraph.cli.cmd_workgraph:workgraph
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=3.4,<4
    - pip
  run:
    - jsonschema
    - node-graph-widget >=0.0.5
    - aiida-pythonjob ==0.4.1
    - python >={{ python_min }}
    - numpy
    - scipy
    - ase
    - node-graph ==0.3.10
    - aiida-core >=2.6,<3.dev0
    - cloudpickle
    - aiida-shell >=0.8,<1.dev0
    - fastapi
    - uvicorn
    - pydantic-settings

test:
  commands:
    - pip check
    - verdi presto --profile-name test
    - python -c "import aiida_workgraph"
    - workgraph --help
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Design flexible node-based workflow for AiiDA calculation.
  home: https://github.com/aiidateam/aiida-workgraph
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - superstar54
    - jan-janssen
