{% set name = "aiida-workgraph" %}
{% set version = "0.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/aiida_workgraph-{{ version }}.tar.gz
  sha256: b6c9d7442b52245114b904711c2124f162255bd3c04f84c59b8e89b981705102

build:
  entry_points:
    - workgraph = aiida_workgraph.cli.cmd_workgraph:workgraph
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=3.4,<4
    - pip
  run:
    - jsonschema
    - node-graph-widget >=0.0.4
    - aiida-pythonjob >=0.2.3
    - python >={{ python_min }}
    - numpy >=1.21,<2.dev0
    - scipy
    - ase
    - node-graph ==0.1.29
    - aiida-core >=2.3
    - cloudpickle
    - aiida-shell >=0.8,<1.dev0
    - fastapi
    - uvicorn
    - pydantic-settings

test:
  commands:
    - pip check
    - verdi presto --profile-name test
    - python -c "import aiida_workgraph"
    - workgraph --help
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Design flexible node-based workflow for AiiDA calculation.
  home: https://github.com/aiidateam/aiida-workgraph
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - superstar54
    - jan-janssen
