{% set name = "aiida-workgraph" %}
{% set version = "0.4.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/aiida_workgraph-{{ version }}.tar.gz
  sha256: 117a1092b1eba0793bc15ea8ab4d52667e7435424fde14402c2c444a24ad6fa6

build:
  entry_points:
    - workgraph = aiida_workgraph.cli.cmd_workgraph:workgraph
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=3.4,<4
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.21,<2.dev0
    - scipy
    - ase
    - node-graph ==0.1.1
    - aiida-core >=2.3
    - cloudpickle
    - aiida-shell >=0.8,<1.dev0
    - fastapi
    - uvicorn
    - pydantic-settings

test:
  imports:
    - aiida_workgraph
  commands:
    - pip check
    - workgraph --help
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Design flexible node-based workflow for AiiDA calculation.
  home: https://github.com/aiidateam/aiida-workgraph
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - superstar54
    - jan-janssen
